import JSZip from 'jszip';
import { IPresentationFile, ISlide, ICanvasSlide } from '@/core/types';

/**
 * Service for importing PowerPoint (.pptx) files and converting them to Ekklesia Presentation (.ektp) format.
 * Fully namespace-agnostic to handle presentations generated by different office suites.
 */
export const PptxImportService = {
    async convert(file: File): Promise<IPresentationFile> {
        try {
            const zip = await JSZip.loadAsync(file);

            // Basic validation of pptx structure
            const presentationXml = zip.file('ppt/presentation.xml');
            if (!presentationXml) {
                throw new Error('Not a valid PowerPoint (.pptx) file');
            }

            // --- Pre-process Media Batch ---
            const mediaFiles = zip.filter((path) => path.startsWith('ppt/media/'));
            const { MediaPersistenceService } = await import('./MediaPersistenceService');
            
            const batchItems: { file: Blob; path: string; type: 'image' | 'audio' | 'video' }[] = [];
            
            for (const mediaFile of mediaFiles) {
                const blob = await mediaFile.async('blob');
                const path = mediaFile.name;
                let type: 'image' | 'audio' | 'video' = 'image';
                const ext = path.split('.').pop()?.toLowerCase();
                if (['mp4', 'webm', 'mov'].includes(ext || '')) type = 'video';
                if (['mp3', 'wav', 'ogg', 'm4a', 'aac', 'flac'].includes(ext || '')) type = 'audio';
                
                batchItems.push({ file: blob, path, type });
            }

            const mediaMap = new Map<string, { id: string; blob: Blob }>();
            if (batchItems.length > 0) {
                const ids = await MediaPersistenceService.importMediaBatch(
                    batchItems.map(b => ({ file: b.file, path: b.path, type: b.type })),
                    { forceBackground: true }
                );
                
                for (let i = 0; i < batchItems.length; i++) {
                    const id = ids[i];
                    if (id) mediaMap.set(batchItems[i].path, { id, blob: batchItems[i].file });
                }
            }

            // Create a skeleton presentation
            const presentation: IPresentationFile = {
                id: `pptx-${crypto.randomUUID()}`,
                name: file.name.replace('.pptx', ''),
                createdAt: new Date(),
                updatedAt: new Date(),
                slides: [],
                metadata: {
                    speaker: 'Imported from PPTX'
                }
            };

            const parser = new DOMParser();
            const presXmlContent = await presentationXml.async('string');
            const presDoc = parser.parseFromString(presXmlContent, 'application/xml');

            // Helper to get attributes in a namespace-agnostic way
            const getAttr = (el: Element | null | undefined, attrName: string): string | null => {
                if (!el) return null;
                const namespaces = [
                    'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
                    'http://schemas.openxmlformats.org/drawingml/2006/main',
                    'http://schemas.openxmlformats.org/presentationml/2006/main'
                ];
                for (const ns of namespaces) {
                    const val = el.getAttributeNS(ns, attrName);
                    if (val !== null && val !== '') return val;
                }
                // Fallback to various prefixed or unprefixed attributes
                return el.getAttribute(attrName) || 
                       el.getAttribute(`r:${attrName}`) || 
                       el.getAttribute(`p:${attrName}`) || 
                       el.getAttribute(`a:${attrName}`);
            };

            // Slide size
            const sldSz = presDoc.getElementsByTagNameNS('*', 'sldSz')[0];
            const slideWidth = parseInt(sldSz?.getAttribute('cx') || '12192000');
            const slideHeight = parseInt(sldSz?.getAttribute('cy') || '6858000');

            // Slide IDs
            const sldIdList = presDoc.getElementsByTagNameNS('*', 'sldId');
            const sldIds = Array.from(sldIdList).map(el => ({
                id: getAttr(el, 'id') || '',
                slideId: el.getAttribute('id')
            }));

            // 2. Resolve slide file paths from presentation.xml.rels
            const presRelsXml = zip.file('ppt/_rels/presentation.xml.rels');
            if (!presRelsXml) throw new Error('Missing ppt/_rels/presentation.xml.rels');
            const presRelsContent = await presRelsXml.async('string');
            const presRelsDoc = parser.parseFromString(presRelsContent, 'application/xml');
            const presRelationships = Array.from(presRelsDoc.getElementsByTagNameNS('*', 'Relationship'));

            const slideFiles = sldIds.map(sld => {
                const rel = presRelationships.find(r => getAttr(r, 'Id') === sld.id);
                return rel ? `ppt/${getAttr(rel, 'Target')}` : null;
            }).filter(Boolean) as string[];

            // Coordinate conversion helper (EMU to percentage 0-100)
            const emuToPercentX = (emu: number) => (emu / slideWidth) * 100;
            const emuToPercentY = (emu: number) => (emu / slideHeight) * 100;
            const BASE_WIDTH = 1920;
            const BASE_HEIGHT = 1080;
            const slideHeightPt = slideHeight / 12700;

            // 4. Resolve Theme Colors
            const themeColors: Record<string, string> = {};
            const themeRel = presRelationships.find(r => getAttr(r, 'Type')?.endsWith('theme'));
            const themePath = themeRel ? `ppt/${getAttr(themeRel, 'Target')}` : 'ppt/theme/theme1.xml';
            const themeFile = zip.file(themePath);
            if (themeFile) {
                const themeXml = await themeFile.async('string');
                const themeDoc = parser.parseFromString(themeXml, 'application/xml');
                const clrScheme = themeDoc.getElementsByTagNameNS('*', 'clrScheme')[0];
                if (clrScheme) {
                    const colorTags = ['dk1', 'lt1', 'dk2', 'lt2', 'accent1', 'accent2', 'accent3', 'accent4', 'accent5', 'accent6', 'hlink', 'folHlink'];
                    for (const tag of colorTags) {
                        const el = clrScheme.getElementsByTagNameNS('*', tag)[0];
                        if (el) {
                            const srgb = el.getElementsByTagNameNS('*', 'srgbClr')[0];
                            const sys = el.getElementsByTagNameNS('*', 'sysClr')[0];
                            if (srgb) themeColors[tag] = `#${srgb.getAttribute('val')}`;
                            else if (sys) themeColors[tag] = `#${sys.getAttribute('lastClr') || (tag.startsWith('lt') ? 'ffffff' : '000000')}`;
                        }
                    }
                }
            }

            // 5. Caches for Layouts and Masters
            const docCache = new Map<string, Document>();
            const getCachedDoc = async (path: string): Promise<Document | null> => {
                if (docCache.has(path)) return docCache.get(path)!;
                const file = zip.file(path);
                if (!file) return null;
                const content = await file.async('string');
                const doc = parser.parseFromString(content, 'application/xml');
                docCache.set(path, doc);
                return doc;
            };

            const getRels = async (path: string): Promise<Record<string, string>> => {
                const parts = path.split('/');
                const fileName = parts.pop();
                const dir = parts.join('/');
                const relPath = `${dir}/_rels/${fileName}.rels`;
                
                const file = zip.file(relPath);
                const rels: Record<string, string> = {};
                if (file) {
                    const content = await file.async('string');
                    const doc = parser.parseFromString(content, 'application/xml');
                    const relEls = doc.getElementsByTagNameNS('*', 'Relationship');
                    for (let r = 0; r < relEls.length; r++) {
                        const relId = getAttr(relEls[r], 'Id');
                        const target = getAttr(relEls[r], 'Target');
                        if (relId && target) {
                            rels[relId] = target;
                        }
                    }
                }
                return rels;
            };

            const resolveColor = (element: Element | undefined | null): string | null => {
                if (!element) return null;
                const solidFill = element.getElementsByTagNameNS('*', 'solidFill')[0];
                if (!solidFill) return null;

                const srgbClr = solidFill.getElementsByTagNameNS('*', 'srgbClr')[0];
                const schemeClr = solidFill.getElementsByTagNameNS('*', 'schemeClr')[0];

                if (srgbClr) {
                    const val = srgbClr.getAttribute('val');
                    return val ? `#${val}` : null;
                } else if (schemeClr) {
                    const val = schemeClr.getAttribute('val');
                    if (!val) return null;
                    if (themeColors[val]) return themeColors[val];
                    // Hardcoded fallbacks
                    const fallbacks: Record<string, string> = {
                        'bg1': '#ffffff', 'lt1': '#ffffff', 'lt2': '#ffffff',
                        'tx1': '#000000', 'dk1': '#000000', 'dk2': '#000000',
                        'accent1': '#4472c4', 'accent2': '#ed7d31'
                    };
                    return fallbacks[val] || null;
                }
                return null;
            };

            const resolveShapeStyleColor = (sp: Element): string | null => {
                const style = sp.getElementsByTagNameNS('*', 'style')[0];
                if (!style) return null;
                const fontRef = style.getElementsByTagNameNS('*', 'fontRef')[0];
                return fontRef ? resolveColor(fontRef) : null;
            };

            const resolveBorder = (spPrEl: Element | null | undefined): { borderColor: string; borderWidth: number } | null => {
                if (!spPrEl) return null;
                const ln = spPrEl.getElementsByTagNameNS('*', 'ln')[0];
                if (!ln) return null;
                const wAttr = ln.getAttribute('w');
                const borderWidth = wAttr ? Math.max(1, Math.round((parseInt(wAttr) / slideHeight) * BASE_HEIGHT)) : 0;
                if (borderWidth === 0) return null;
                const borderColor = resolveColor(ln);
                if (!borderColor) return null;
                return { borderColor, borderWidth };
            };

            // 6. Iterate over slides
            for (let i = 0; i < slideFiles.length; i++) {
                const slidePath = slideFiles[i];
                const slideXml = zip.file(slidePath);
                if (!slideXml) continue;

                const slideContent = await slideXml.async('string');
                const slideDoc = parser.parseFromString(slideContent, 'application/xml');

                const slide: ICanvasSlide = {
                    id: crypto.randomUUID(),
                    type: 'normal',
                    order: i,
                    blockId: 'presentation',
                    templateId: 'blank-dark',
                    content: {
                        variables: {},
                        canvasItems: []
                    }
                };

                const slideRelationships = await getRels(slidePath);

                // Find Layout and Master for inheritance
                let layoutDoc: Document | null = null;
                let masterDoc: Document | null = null;
                let layoutRels: Record<string, string> = {};
                let masterRels: Record<string, string> = {};

                const layoutRel = Object.values(slideRelationships).find(t => t.includes('slideLayout'));
                if (layoutRel) {
                    const layoutPath = `ppt/${layoutRel.replace('../', '')}`;
                    layoutDoc = await getCachedDoc(layoutPath);
                    if (layoutDoc) {
                        layoutRels = await getRels(layoutPath);
                        const masterRel = Object.values(layoutRels).find(t => t.includes('slideMaster'));
                        if (masterRel) {
                            const masterPath = `ppt/${masterRel.replace('../', '')}`;
                            masterDoc = await getCachedDoc(masterPath);
                            if (masterDoc) {
                                masterRels = await getRels(masterPath);
                            }
                        }
                    }
                }

                // Resolve Relationship - checks slide, layout, and master relationships hierarchically
                const resolveRel = (rId: string | null) => {
                    if (!rId) return null;
                    const target = slideRelationships[rId] || layoutRels[rId] || masterRels[rId];
                    if (!target) return null;
                    // Normalize path relative to ppt/slides/
                    const mediaPath = target.startsWith('../media/')
                        ? `ppt/media/${target.substring('../media/'.length)}`
                        : target.startsWith('..')
                            ? `ppt/${target.substring(3)}`
                            : `ppt/slides/${target}`;
                    if (mediaMap.has(mediaPath)) return mediaMap.get(mediaPath)!;
                    const fileName = target.split('/').pop();
                    const fallbackPath = `ppt/media/${fileName}`;
                    return mediaMap.get(fallbackPath) || null;
                };

                // Hierarchical Style Inheritor
                const getInheritedShape = (phType: string | null, phIdx: string | null, doc: Document | null): Element | null => {
                    if (!doc) return null;
                    const shapes = doc.getElementsByTagNameNS('*', 'sp');
                    for (let s = 0; s < shapes.length; s++) {
                        const ph = shapes[s].getElementsByTagNameNS('*', 'ph')[0];
                        if (ph) {
                            if (phType && ph.getAttribute('type') === phType) return shapes[s];
                            if (phIdx && ph.getAttribute('idx') === phIdx) return shapes[s];
                        }
                    }
                    return null;
                };

                // Image Processor
                const processPic = async (pic: Element, index: number) => {
                    const blip = pic.getElementsByTagNameNS('*', 'blip')[0];
                    const media = resolveRel(getAttr(blip, 'embed'));
                    if (!media) return;

                    const nvPr = pic.getElementsByTagNameNS('*', 'nvPr')[0];
                    const ph = nvPr?.getElementsByTagNameNS('*', 'ph')[0];
                    const phType = ph?.getAttribute('type');
                    const phIdx = ph?.getAttribute('idx');

                    const spPr = pic.getElementsByTagNameNS('*', 'spPr')[0];
                    let xfrm = spPr?.getElementsByTagNameNS('*', 'xfrm')[0];

                    if ((!xfrm || !xfrm.getElementsByTagNameNS('*', 'off')[0] || !xfrm.getElementsByTagNameNS('*', 'ext')[0]) && ph) {
                        const layoutSp = getInheritedShape(phType, phIdx, layoutDoc);
                        if (layoutSp) {
                            const lSpPr = layoutSp.getElementsByTagNameNS('*', 'spPr')[0];
                            const lXfrm = lSpPr?.getElementsByTagNameNS('*', 'xfrm')[0];
                            if (lXfrm && lXfrm.getElementsByTagNameNS('*', 'off')[0] && lXfrm.getElementsByTagNameNS('*', 'ext')[0]) {
                                xfrm = lXfrm;
                            }
                        }
                        if (!xfrm) {
                            const masterSp = getInheritedShape(phType, phIdx, masterDoc);
                            if (masterSp) {
                                const mSpPr = masterSp.getElementsByTagNameNS('*', 'spPr')[0];
                                const mXfrm = mSpPr?.getElementsByTagNameNS('*', 'xfrm')[0];
                                if (mXfrm && mXfrm.getElementsByTagNameNS('*', 'off')[0] && mXfrm.getElementsByTagNameNS('*', 'ext')[0]) {
                                    xfrm = mXfrm;
                                }
                            }
                        }
                    }

                    const off = xfrm?.getElementsByTagNameNS('*', 'off')[0];
                    const ext = xfrm?.getElementsByTagNameNS('*', 'ext')[0];
                    if (!off || !ext) return;

                    const x = emuToPercentX(parseInt(off.getAttribute('x') || '0'));
                    const y = emuToPercentY(parseInt(off.getAttribute('y') || '0'));
                    const w = emuToPercentX(parseInt(ext.getAttribute('cx') || '0'));
                    const h = emuToPercentY(parseInt(ext.getAttribute('cy') || '0'));
                    const rot = parseInt(xfrm?.getAttribute('rot') || '0');

                    let border: { borderColor: string; borderWidth: number } | null = null;
                    const spPrs = [spPr];
                    if (ph) {
                        const layoutSp = getInheritedShape(phType, phIdx, layoutDoc);
                        if (layoutSp) spPrs.push(layoutSp.getElementsByTagNameNS('*', 'spPr')[0]);
                        const masterSp = getInheritedShape(phType, phIdx, masterDoc);
                        if (masterSp) spPrs.push(masterSp.getElementsByTagNameNS('*', 'spPr')[0]);
                    }
                    for (const pr of spPrs) {
                        if (pr) {
                            border = resolveBorder(pr);
                            if (border) break;
                        }
                    }

                    slide.content.canvasItems = slide.content.canvasItems || [];
                    slide.content.canvasItems.push({
                        id: crypto.randomUUID(),
                        type: 'image',
                        x: x + w / 2, y: y + h / 2,
                        width: w, height: h,
                        rotation: rot / 60000,
                        zIndex: index,
                        pivotX: 50, pivotY: 50,
                        locked: false, visible: true,
                        image: { id: media.id, isFromDb: true },
                        fills: [],
                        strokes: [],
                        ...(border ? { borderColor: border.borderColor, borderWidth: border.borderWidth } : {})
                    });
                };

                // Shape Processor (Text + Backfills)
                const processShape = async (sp: Element, index: number) => {
                    const blipFill = sp.getElementsByTagNameNS('*', 'blipFill')[0];
                    if (blipFill) {
                        await processPic(sp, index);
                        return;
                    }

                    const nvPr = sp.getElementsByTagNameNS('*', 'nvPr')[0];
                    const ph = nvPr?.getElementsByTagNameNS('*', 'ph')[0];
                    const phType = ph?.getAttribute('type');
                    const phIdx = ph?.getAttribute('idx');

                    const spPr = sp.getElementsByTagNameNS('*', 'spPr')[0];
                    let xfrm = spPr?.getElementsByTagNameNS('*', 'xfrm')[0];

                    const inheritedSps: Element[] = [];
                    if (ph) {
                        const layoutSp = getInheritedShape(phType, phIdx, layoutDoc);
                        if (layoutSp) inheritedSps.push(layoutSp);
                        const masterSp = getInheritedShape(phType, phIdx, masterDoc);
                        if (masterSp) inheritedSps.push(masterSp);
                    }

                    const getFormatting = (rPr: Element | null, defRPr: Element | null, endParaRPr: Element | null, inheritedSps: Element[]) => {
                        let rBold = false;
                        let rItalic = false;
                        let rUnderline = false;
                        let rStrike = false;
                        let rColor: string | null = null;
                        let rSize: number | null = null;
                        let rFont: string | null = null;

                        const checkEl = (el: Element | null | undefined) => {
                            if (!el) return;
                            
                            const b = el.getAttribute('b');
                            if (b === '1' || b === 'true') rBold = true;
                            else if (b === '0' || b === 'false') rBold = false;
                            
                            const i = el.getAttribute('i');
                            if (i === '1' || i === 'true') rItalic = true;
                            else if (i === '0' || i === 'false') rItalic = false;
                            
                            const u = el.getAttribute('u');
                            if (u && u !== 'none') rUnderline = true;
                            else if (u === 'none') rUnderline = false;
                            
                            const strike = el.getAttribute('strike');
                            if (strike && strike !== 'noStrike') rStrike = true;
                            else if (strike === 'noStrike') rStrike = false;
                            
                            const sz = el.getAttribute('sz');
                            if (sz && !rSize) rSize = parseInt(sz) / 100;
                            
                            const latin = el.getElementsByTagNameNS('*', 'latin')[0];
                            const typeface = latin?.getAttribute('typeface');
                            if (typeface && !typeface.startsWith('+') && !rFont) {
                                rFont = typeface;
                            }
                            
                            if (!rColor) {
                                rColor = resolveColor(el);
                            }
                        };

                        checkEl(rPr);
                        checkEl(endParaRPr);
                        checkEl(defRPr);

                        for (const sp of inheritedSps) {
                            const inheritedTxBody = sp.getElementsByTagNameNS('*', 'txBody')[0];
                            if (inheritedTxBody) {
                                const bodyPara = inheritedTxBody.getElementsByTagNameNS('*', 'p')[0];
                                const bodyDefRPr = bodyPara?.getElementsByTagNameNS('*', 'pPr')[0]?.getElementsByTagNameNS('*', 'defRPr')[0];
                                checkEl(bodyDefRPr);
                                
                                const bodyRPr = bodyPara?.getElementsByTagNameNS('*', 'rPr')[0];
                                checkEl(bodyRPr);
                            }
                            if (!rColor) {
                                rColor = resolveShapeStyleColor(sp);
                            }
                        }

                        return { rBold, rItalic, rUnderline, rStrike, rColor, rSize, rFont };
                    };

                    const off = xfrm?.getElementsByTagNameNS('*', 'off')[0];
                    const ext = xfrm?.getElementsByTagNameNS('*', 'ext')[0];
                    if (!off || !ext) return;

                    const x = emuToPercentX(parseInt(off.getAttribute('x') || '0'));
                    const y = emuToPercentY(parseInt(off.getAttribute('y') || '0'));
                    const w = emuToPercentX(parseInt(ext.getAttribute('cx') || '0'));
                    const h = emuToPercentY(parseInt(ext.getAttribute('cy') || '0'));
                    const rot = parseInt(xfrm?.getAttribute('rot') || '0');

                    const txBody = sp.getElementsByTagNameNS('*', 'txBody')[0];
                    if (txBody) {
                        const paragraphs = Array.from(txBody.getElementsByTagNameNS('*', 'p'));
                        let fullText = '';
                        let fontFamily = 'Inter';
                        let ptSize = 18;
                        let textColor: string | null = null;
                        let isBold = false;
                        let isItalic = false;
                        let isUnderline = false;
                        let isStrikethrough = false;
                        let hasParsedFormatting = false;
                        
                        // Vertical Anchor
                        const bodyPr = txBody.getElementsByTagNameNS('*', 'bodyPr')[0];
                        const anchor = bodyPr?.getAttribute('anchor');
                        let alignVertical: 'top' | 'middle' | 'bottom' = 'middle';
                        if (anchor === 't') alignVertical = 'top';
                        if (anchor === 'b') alignVertical = 'bottom';

                        // Horizontal Alignment (from 1st para)
                        const firstAlgn = paragraphs[0]?.getElementsByTagNameNS('*', 'pPr')[0]?.getAttribute('algn');
                        let alignHorizontal: 'left' | 'center' | 'right' | 'justify' = 'center';
                        if (firstAlgn === 'l') alignHorizontal = 'left';
                        if (firstAlgn === 'r') alignHorizontal = 'right';
                        if (firstAlgn === 'just') alignHorizontal = 'justify';

                        const lines: string[] = [];
                        for (const para of paragraphs) {
                            let line = '';
                            const runs = Array.from(para.childNodes);
                            for (const node of runs) {
                                const el = node as Element;
                                if (el.localName === 'r') {
                                    const t = el.getElementsByTagNameNS('*', 't')[0]?.textContent || '';
                                    line += t;
                                    
                                    if (t.trim() && !hasParsedFormatting) {
                                        const rPr = el.getElementsByTagNameNS('*', 'rPr')[0];
                                        const defRPr = para.getElementsByTagNameNS('*', 'pPr')[0]?.getElementsByTagNameNS('*', 'defRPr')[0];
                                        const endParaRPr = para.getElementsByTagNameNS('*', 'endParaRPr')[0];
                                        
                                        const fmt = getFormatting(rPr, defRPr, endParaRPr, inheritedSps);
                                        isBold = fmt.rBold;
                                        isItalic = fmt.rItalic;
                                        isUnderline = fmt.rUnderline;
                                        isStrikethrough = fmt.rStrike;
                                        if (fmt.rColor) textColor = fmt.rColor;
                                        if (fmt.rSize) ptSize = fmt.rSize;
                                        if (fmt.rFont) fontFamily = fmt.rFont;
                                        
                                        hasParsedFormatting = true;
                                        
                                        // If we still don't have color, fallback to shape/style
                                        if (!textColor) {
                                            textColor = resolveShapeStyleColor(sp);
                                            for (const isp of inheritedSps) {
                                                if (!textColor) textColor = resolveShapeStyleColor(isp);
                                            }
                                        }
                                    }
                                } else if (el.localName === 'br') {
                                    line += '\n';
                                }
                            }
                            if (line.trim() || line === '') lines.push(line);
                        }
                        fullText = lines.join('\n');

                        if (!hasParsedFormatting && paragraphs.length > 0) {
                            const firstPara = paragraphs[0];
                            const defRPr = firstPara?.getElementsByTagNameNS('*', 'pPr')[0]?.getElementsByTagNameNS('*', 'defRPr')[0];
                            const endParaRPr = firstPara?.getElementsByTagNameNS('*', 'endParaRPr')[0];
                            const fmt = getFormatting(null, defRPr, endParaRPr, inheritedSps);
                            isBold = fmt.rBold;
                            isItalic = fmt.rItalic;
                            isUnderline = fmt.rUnderline;
                            isStrikethrough = fmt.rStrike;
                            if (fmt.rColor) textColor = fmt.rColor;
                            if (fmt.rSize) ptSize = fmt.rSize;
                            if (fmt.rFont) fontFamily = fmt.rFont;
                        }

                        if (fullText.trim()) {
                            const scaledFontSize = Math.round(ptSize * (BASE_HEIGHT / slideHeightPt));
                            if (!textColor) textColor = themeColors['tx1'] || themeColors['dk1'] || '#000000';

                            slide.content.canvasItems = slide.content.canvasItems || [];
                            
                            const spPrFill = resolveColor(spPr);
                            const fills: any[] = [];
                            if (spPrFill) {
                                fills.push({ id: crypto.randomUUID(), type: 'color', visible: true, opacity: 1, blendMode: 'normal', color: spPrFill });
                            }

                            let border: { borderColor: string; borderWidth: number } | null = null;
                            const spPrs = [spPr];
                            for (const isp of inheritedSps) {
                                spPrs.push(isp.getElementsByTagNameNS('*', 'spPr')[0]);
                            }
                            for (const pr of spPrs) {
                                if (pr) {
                                    border = resolveBorder(pr);
                                    if (border) break;
                                }
                            }

                            slide.content.canvasItems.push({
                                id: crypto.randomUUID(),
                                type: 'text',
                                x: x + w / 2, y: y + h / 2,
                                width: w, height: h,
                                rotation: rot / 60000,
                                zIndex: index,
                                pivotX: 50, pivotY: 50,
                                locked: false, visible: true,
                                fills, strokes: [],
                                ...(border ? { borderColor: border.borderColor, borderWidth: border.borderWidth } : {}),
                                text: {
                                    content: fullText,
                                    fontFamily, fontWeight: isBold ? 'bold' : 'normal',
                                    fontSize: scaledFontSize || 32,
                                    color: textColor,
                                    textFills: [{ id: crypto.randomUUID(), type: 'color', visible: true, opacity: 1, blendMode: 'normal', color: textColor }],
                                    resizingMode: 'fixed',
                                    alignHorizontal, alignVertical,
                                    isBold,
                                    isItalic,
                                    isUnderline,
                                    isStrikethrough
                                }
                            });
                        }
                    }
                };

                const resolveBackground = () => {
                    const bgs = [
                        { bg: slideDoc.getElementsByTagNameNS('*', 'bg')[0], rels: slideRelationships },
                        { bg: layoutDoc?.getElementsByTagNameNS('*', 'bg')[0], rels: layoutRels },
                        { bg: masterDoc?.getElementsByTagNameNS('*', 'bg')[0], rels: masterRels }
                    ].filter(item => item.bg);

                    for (const { bg, rels } of bgs) {
                        if (!bg) continue;
                        
                        const blipFill = bg.getElementsByTagNameNS('*', 'bgPicProps')[0] || bg.getElementsByTagNameNS('*', 'blipFill')[0];
                        const blip = blipFill?.getElementsByTagNameNS('*', 'blip')[0];
                        const rId = getAttr(blip, 'embed');
                        if (rId) {
                            const target = rels[rId];
                            if (target) {
                                let mediaPath = target.startsWith('..') ? `ppt/${target.substring(3)}` : `ppt/${target}`;
                                let mediaFile = zip.file(mediaPath) || zip.file(`ppt/media/${target.split('/').pop()}`);

                                if (mediaFile) {
                                    const media = mediaMap.get(mediaPath)
                                        || mediaMap.get(`ppt/media/${target.split('/').pop()}`);
                                    if (media) {
                                        slide.content.canvasItems = slide.content.canvasItems || [];
                                        slide.content.canvasItems.unshift({
                                            id: crypto.randomUUID(),
                                            type: 'image',
                                            x: 50, y: 50,
                                            width: 100, height: 100,
                                            rotation: 0,
                                            zIndex: 0,
                                            pivotX: 50, pivotY: 50,
                                            locked: true,
                                            visible: true,
                                            image: { id: media.id, isFromDb: true },
                                            fills: [],
                                            strokes: []
                                        });
                                        return true;
                                    }
                                }
                            }
                        }

                        const bgPr = bg.getElementsByTagNameNS('*', 'bgPr')[0];
                        const color = resolveColor(bgPr || bg);
                        if (color) {
                            slide.backgroundOverride = [{
                                id: crypto.randomUUID(),
                                type: 'color',
                                visible: true,
                                opacity: 1,
                                blendMode: 'normal',
                                color,
                            }];
                            return true;
                        }
                    }
                    return false;
                };

                resolveBackground();

                const spTree = slideDoc.getElementsByTagNameNS('*', 'spTree')[0];
                if (spTree) {
                    const children = Array.from(spTree.children);
                    for (let j = 0; j < children.length; j++) {
                        const child = children[j];
                        const localName = child.localName;
                        if (localName === 'sp') {
                            await processShape(child, j + 1);
                        } else if (localName === 'pic') {
                            await processPic(child, j + 1);
                        } else if (localName === 'grpSp') {
                            const grpPics = Array.from(child.getElementsByTagNameNS('*', 'pic'));
                            const grpShapes = Array.from(child.getElementsByTagNameNS('*', 'sp'));
                            for (const pic of grpPics) await processPic(pic, j + 1);
                            for (const sp of grpShapes) await processShape(sp, j + 1);
                        }
                    }
                }

                presentation.slides.push(slide);
            }

            return presentation;
        } catch (error) {
            throw error;
        }
    }
};
